export const AUTO_GENERATE_DISCLAIMER = [
  "/*",
  " * This file is automatically generated.",
  " * Manual changes will be lost.",
  " */",
].join("\n");

export const BUTTON_SHADE_NAMES = [
  "-minor-2",
  "-minor-1",
  "",
  "-major-1",
  "-major-2",
  "-major-3",
  "-contrast",
];

export const CONFIG_FILES = [
  "freyja.config.js",
  "freyja.config.mjs",
  "freyja.config.cjs",
  "freyja.config.ts",
  "freyja.config.mts",
  "freyja.config.cts",
];
