import {readFileSync} from "node:fs";

const {version} = JSON.parse(
  readFileSync(new URL("../package.json", import.meta.url)).toString(),
);

export const FREYR_VERSION = version as string;

export const CONFIG_FILES = [
  "freyr.config.js",
  "freyr.config.mjs",
  "freyr.config.cjs",
  "freyr.config.ts",
  "freyr.config.mts",
  "freyr.config.cts"
];

export const AUTO_GENERATE_DISCLAIMER = [
  "/*",
  " * This file is automatically generated.",
  " * Manual changes will be lost.",
  " */",
].join("\n");
