name: Unit Tests
on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Cache node modules
        uses: actions/cache@v3
        id: modules-cache
        with:
          path: "node_modules"
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Cache Nx
        uses: actions/cache@v2
        with:
          path: .nx
          key: nx-${{ hashFiles('yarn.lock') }}-${{ github.sha }}
          restore-keys: nx-${{ hashFiles('yarn.lock') }}-

      - name: Install packages
        if: steps.modules-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build
        run: yarn build

      - name: Run test
        run: yarn test
